name: "General Testing"
on:
  - push
  - pull_request

permissions:
  contents: read
  pull-requests: read

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet 9.0
        uses: actions/setup-dotnet@v4
        with:
            dotnet-version: 9.0
      - name: Test with the dotnet CLI
        run: dotnet test
